/usr/local/lib/desltop-session/desktop-session-restart Space-IceWM
killall conky
sudo apt-get purge abcde
sudo apt-get purge asunder
sudo apt-get purge calcurse
sudo apt-get purge cdparanoia
sudo apt-get purge celluloid
sudo apt-get purge ceni
sudo apt-get purge cherrytree
sudo apt-get purge claws-mail
sudo apt-get purge clipit
sudo apt-get purge conky-legacy-all
sudo apt-get purge connectshares-antix
sudo apt-get purge dillo
sudo apt-get purge dosbox
sudo apt-get purge droopy-antix
sudo apt-get purge e3
sudo apt-get purge eject
sudo apt-get purge elinks
sudo apt-get purge elinks-data
sudo apt-get purge firejail
sudo apt-get purge firejail-profiles
sudo apt-get purge firetools
sudo apt-get purge fluxbox
sudo apt-get purge fluxbox-base-themes-antix
sudo apt-get purge galternatives
sudo apt-get purge geany
sudo apt-get purge geany-common
sudo apt-get purge gftp-common
sudo apt-get purge gftp-gtk
sudo apt-get purge gifsicle
sudo apt-get purge gnome-mahjongg
sudo apt-get purge gnome-ppp
sudo apt-get purge grsync
sudo apt-get purge gtkam
sudo apt-get purge gufw-legacy
sudo apt-get purge guvcview
sudo apt-get purge gweled
sudo apt-get purge herbstluftwm
sudo apt-get purge hexchat
sudo apt-get purge hexchat-common
sudo apt-get purge html2text
sudo apt-get purge hunspell-ca
sudo apt-get purge hunspell-cs
sudo apt-get purge hunspell-da
sudo apt-get purge hunspell-de-de
sudo apt-get purge hunspell-el
sudo apt-get purge hunspell-en-au
sudo apt-get purge hunspell-en-ca
sudo apt-get purge hunspell-nl
sudo apt-get purge hunspell-pl
sudo apt-get purge hunspell-pt-pt
sudo apt-get purge hunspell-ru
sudo apt-get purge hunspell-sv
sudo apt-get purge icedax
sudo apt-get purge iftop
sudo apt-get purge irssi
sudo apt-get purge irssi-plugin-otr
sudo apt-get purge irssi-scripts
sudo apt-get purge jwm
sudo apt-get purge links2
sudo apt-get purge luckybackup
sudo apt-get purge mc
sudo apt-get purge mcedit
sudo apt-get purge modem-manager
sudo apt-get purge modem-manager-gui
sudo apt-get purge modem-manager-gui
sudo apt-get purge mpsyt
sudo apt-get purge mps-youtube
sudo apt-get purge mpv
sudo apt-get purge mtpaint
sudo apt-get purge mupdf
sudo apt-get purge newsboat
sudo apt-get purge niroki-theme-antix
sudo apt-get purge normalize-audio
sudo apt-get purge numix-gtk-theme
sudo apt-get purge numix-square-antix
sudo apt-get purge ofono
sudo apt-get purge oxygen-black-cursor-theme-antix
sudo apt-get purge oxygen-white-cursor-theme-antix
sudo apt-get purge pmrp
sudo apt-get purge ppp
sudo apt-get purge pppoeconf
sudo apt-get purge prettypink-themes
sudo apt-get purge radeontool
sudo apt-get purge rox-filer
sudo apt-get purge search-bar
sudo apt-get purge searchmonkey
sudo apt-get purge smtube
sudo apt-get purge sox
sudo apt-get purge streamlight-antix
sudo apt-get purge streamlink
sudo apt-get purge streamtuner2
sudo apt-get purge umts-panel2
sudo apt-get purge urxvt
sudo apt-get purge vim-tiny
sudo apt-get purge vim-common
sudo apt-get purge wamerican
sudo apt-get purge winff
sudo apt-get purge winff-data
sudo apt-get purge winff-doc
sudo apt-get purge winff-gtk2
sudo apt-get purge winff-doc
sudo apt-get purge wodim
sudo apt-get purge xfburn
sudo apt-get purge xlinks2
sudo apt-get purge xmms
sudo apt-get purge youtube-dl
sudo apt autoremove
